/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.persa.views;

import co.edu.sena.examplejpa.utils.MessageUtils;
import co.edu.sena.persa.controllers.CareerControllers;
import co.edu.sena.persa.controllers.CourseController;
import co.edu.sena.persa.controllers.ICareerControllers;
import co.edu.sena.persa.controllers.ICourseControllers;
import co.edu.sena.persa.model.Career;
import co.edu.sena.persa.model.Course;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Sebas
 */
public class JFrameCourses extends javax.swing.JFrame {
    private ICourseControllers courseeController = new CourseController();
    private ICareerControllers  careerController = new CareerControllers();
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy");

    /**
     * Creates new form JFrameCourses
     */
    public JFrameCourses() {
        initComponents();
        fillCombos();
        fillTable();
    }
    
    public void fillCombos()
    {
        try {
//            List<Course> employees = courseController.findAll();
//            DefaultComboBoxModel model = new DefaultComboBoxModel();
//            jComboBoxShift.setModel(model);
//            model.addAll(employees);
            
            List<Career> career = careerController.findALL();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            jComboBoxCareer.setModel(model);
            model.addAll(career);
            
        } catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
            
    }

    public void fillTable()
    {
        try {
            DefaultTableModel model = new DefaultTableModel();
            jTableCourses.setModel(model);
            model.addColumn("Id");
            model.addColumn("Programa");
            model.addColumn("Trimestre");
            model.addColumn("Jornada");
            model.addColumn("Estado");
            model.addColumn("Año");
            
            String [] rows = new String[6];
            List<Course> course = courseeController.findALL();
            for (Course c : course) {
                rows[0] = String.valueOf(c.getId());
                rows[1] = c.getCareerId().getName();
                rows[2] = c.getTrimester();
                rows[3] = c.getShift();
                rows[4] = c.getStatus();
                rows[5] = sdf.format(c.getYear());
                
                model.addRow(rows);
            }
        } catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jPanelBody = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelIconSena = new javax.swing.JLabel();
        jLabelIconPersa = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCourses = new javax.swing.JTable();
        jButtonAdd1 = new javax.swing.JButton();
        jButtonUpdate1 = new javax.swing.JButton();
        jButtonClean1 = new javax.swing.JButton();
        jButtonDelete1 = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelTrimester = new javax.swing.JLabel();
        jComboBoxTrimester = new javax.swing.JComboBox<>();
        jLabelStatus = new javax.swing.JLabel();
        jLabelCareer = new javax.swing.JLabel();
        jLabelYear = new javax.swing.JLabel();
        jLabelShift = new javax.swing.JLabel();
        jComboBoxShift = new javax.swing.JComboBox<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jComboBoxCareer = new javax.swing.JComboBox<>();
        jTextFieldYear = new javax.swing.JTextField();

        jButtonAdd.setBackground(new java.awt.Color(57, 169, 0));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("CREAR");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonUpdate.setBackground(new java.awt.Color(51, 51, 255));
        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("ACTUALIZAR");
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonClean.setBackground(new java.awt.Color(255, 255, 153));
        jButtonClean.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClean.setText("LIMPIAR");
        jButtonClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("ELIMINAR");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COURSES");

        jPanelBody.setBackground(new java.awt.Color(4, 135, 4));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setText("CURSOS");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/persa/view/LogoSena.jpeg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/persa/view/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabelIconSena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(183, 183, 183)))
                .addComponent(jLabelIconPersa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(jLabelIconSena)
                .addGap(22, 22, 22)
                .addComponent(jLabelTitle))
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelIconPersa))
            .addComponent(jLabel1)
            .addComponent(jLabel2)
        );

        jTableCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCoursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCourses);

        jButtonAdd1.setBackground(new java.awt.Color(57, 169, 0));
        jButtonAdd1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAdd1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd1.setText("CREAR");
        jButtonAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdd1ActionPerformed(evt);
            }
        });

        jButtonUpdate1.setBackground(new java.awt.Color(51, 51, 255));
        jButtonUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonUpdate1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate1.setText("ACTUALIZAR");
        jButtonUpdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate1ActionPerformed(evt);
            }
        });

        jButtonClean1.setBackground(new java.awt.Color(255, 255, 153));
        jButtonClean1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClean1.setText("LIMPIAR");
        jButtonClean1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClean1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClean1ActionPerformed(evt);
            }
        });

        jButtonDelete1.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDelete1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete1.setText("ELIMINAR");
        jButtonDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete1ActionPerformed(evt);
            }
        });

        jLabelId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelId.setText("Id: ");

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jLabelTrimester.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTrimester.setText("Trimestre:");

        jComboBoxTrimester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T1 ", "T2", "T3", "T4" }));

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelStatus.setText("Estado:");

        jLabelCareer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCareer.setText("Programa:");

        jLabelYear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelYear.setText("Año:");

        jLabelShift.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelShift.setText("Jornada:");

        jComboBoxShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIURNA ", "NOCTURNA ", "MIXTA" }));

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));

        jTextFieldYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addComponent(jLabelStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCareer)
                                    .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldId)
                                    .addComponent(jComboBoxCareer, 0, 174, Short.MAX_VALUE)))
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelShift)
                                    .addComponent(jLabelTrimester)
                                    .addComponent(jLabelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxTrimester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxShift, 0, 176, Short.MAX_VALUE)))))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonAdd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate1)
                        .addGap(20, 20, 20)))
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonClean1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelete1)))
                .addGap(37, 37, 37))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCareer)
                            .addComponent(jComboBoxCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStatus)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelYear)
                            .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTrimester)
                            .addComponent(jComboBoxTrimester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelShift)
                            .addComponent(jComboBoxShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClean1)
                            .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonDelete1)
                                .addComponent(jButtonUpdate1)
                                .addComponent(jButtonAdd1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCoursesMouseClicked
        int rowSelected = jTableCourses.getSelectedRow();
        if(rowSelected != -1)
        {
            long idSelected = Long.parseLong(jTableCourses.getValueAt(rowSelected, 0).toString());
            try {
                Course c = courseeController.findById(idSelected);
                jTextFieldId.setText(String.valueOf(idSelected));
                jTextFieldYear.setText(sdf.format(c.getYear()));
                jComboBoxCareer.getModel().setSelectedItem(c.getCareerId().getName());
                jComboBoxStatus.getModel().setSelectedItem(c.getStatus());
                jComboBoxShift.getModel().setSelectedItem(c.getShift());
                jComboBoxTrimester.getModel().setSelectedItem(c.getTrimester());

                jButtonAdd.setEnabled(false);
                jButtonUpdate.setEnabled(true);
                jButtonDelete.setEnabled(true);
            } catch (Exception e) {
                MessageUtils.showInfoMessage(e.getMessage());
            }
            } 
    }//GEN-LAST:event_jTableCoursesMouseClicked

    private void jButtonClean1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClean1ActionPerformed
       clean();
    }//GEN-LAST:event_jButtonClean1ActionPerformed

    private void jButtonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd1ActionPerformed
        try {
            Course course = new Course();
            course.setId(Long.parseLong(jTextFieldId.getText()));
            course.setStatus(jComboBoxStatus.getSelectedItem().toString());
            course.setTrimester(jComboBoxTrimester.getSelectedItem().toString());
            course.setShift(jComboBoxShift.getSelectedItem().toString());
            String yearStr = jTextFieldYear.getText().trim();
            Date year = sdf.parse(yearStr); 
            course.setYear(year);
            
            Career career = (Career) jComboBoxCareer.getSelectedItem();
            course.setCareerId(career);
            
            courseeController.insert(course);
            MessageUtils.showInfoMessage("El curso creado exitosamente");
            fillTable();
            clean();
            
        } catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonAdd1ActionPerformed

    private void jButtonUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate1ActionPerformed
        try {
            Course course = new Course();
            course.setId(Long.parseLong(jTextFieldId.getText()));
            course.setStatus(jComboBoxStatus.getSelectedItem().toString());
            course.setTrimester(jComboBoxTrimester.getSelectedItem().toString());
            course.setShift(jComboBoxShift.getSelectedItem().toString());
            String yearStr = jTextFieldYear.getText().trim();
            Date year = sdf.parse(yearStr); 
            course.setYear(year);
            
            Career career = (Career) jComboBoxCareer.getSelectedItem();
            course.setCareerId(career);
           
            courseeController.update(course);
            MessageUtils.showInfoMessage("El curso fue actualizado exitosamente");
            fillTable();
            clean();
            
        } catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdate1ActionPerformed

    private void jButtonDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete1ActionPerformed
        try {
            int option = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de eliminar el registro?", 
                         "Confirmacion", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION)
            {
                courseeController.delete(Long.parseLong(jTextFieldId.getText()));
                MessageUtils.showInfoMessage("El curso fue eliminado exitosamente");
                fillTable();
            }
            clean();
        } catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonDelete1ActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jTextFieldYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldYearActionPerformed

    
    public void clean()
    {
        jTextFieldId.setText("");
        jTextFieldYear.setText("");
        jComboBoxCareer.setSelectedIndex(0);
        jComboBoxStatus.setSelectedIndex(0);
        jTableCourses.clearSelection();
        jComboBoxShift.setSelectedIndex(0);
        jComboBoxTrimester.setSelectedIndex(0);
        jButtonAdd.setEnabled(true);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAdd1;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonClean1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDelete1;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonUpdate1;
    private javax.swing.JComboBox<String> jComboBoxCareer;
    private javax.swing.JComboBox<String> jComboBoxShift;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxTrimester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCareer;
    private javax.swing.JLabel jLabelIconPersa;
    private javax.swing.JLabel jLabelIconSena;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelShift;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTrimester;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCourses;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
}
